name = "GACODE"
uuid = "bb074124-7a58-47ce-bd41-6b7098184f23"
authors = ["Orso Meneghini <orso82@gmail.com>"]
version = "1.0.7"

[deps]
IMAS = "13ead8c1-b7d1-41bb-a6d0-5b8b65ed587a"
IMASutils = "b8e4ee59-9bed-3a6a-a553-8dd24d6374ad"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
IMAS = "3, 4, 5, 6, 7"
IMASutils = "1.5.1"
Printf = "1.11.0"
julia = "1"
